language: java
notifications:
  slack:
    secure: hJX5mQYtf+aCgM3gPlC+7XunT3IfSdqzhM3YCjsJfKN/Sdf8qvusN1t1E61cCyrjnygXTao2XLODVJ5hou0dtpeRRx53AR4BlUFe3HBCcG2yVJYiTpPPkpyyheJkjJIfVmbLvnpF77b1qG/RdIyaiwsZqEv6lXptcpkBXd/pvsk=
deploy:
  provider: releases
  api_key:
    secure: gIL0pqrRqT/eFMzhrSjDPBERtosG52z56H36roNhjGeH+k1ZlPdmTMcum6gk6i9Ldya40ag15ukOFQicPNAqXORWf2YjgcZW6FAe8YDSz8vZj9DXJmOep+icdeJC46hOZlMGVKUGnYk/us4EKcKK3P5ZSYvzJcoCk0/0VA5j+BM=
  file: build/libs/xld-dar-importer-plugin-1.0.jar
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
    repo: xebialabs-community/xld-dar-importer-plugin
